# Generated by Django 4.2.1 on 2025-08-31 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_service', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HotelService',
        ),
    ]
